# Generated by Django 5.2.17 on 2026-08-14 19:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

import knowledge.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.CharField(default=knowledge.models.default_uuid, max_length=64, primary_key=True, serialize=False)),
                ('source_path', models.CharField(max_length=1000, unique=True)),
                ('original_filename', models.CharField(max_length=500)),
                ('media_type', models.CharField(max_length=50)),
                ('content_hash', models.CharField(db_index=True, max_length=64)),
                ('byte_size', models.BigIntegerField(default=0)),
                ('status', models.CharField(default='indexed', max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('indexed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notebook',
            fields=[
                ('id', models.CharField(default=knowledge.models.default_uuid, max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('position', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'notebooks',
                'ordering': ['position', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.CharField(default=knowledge.models.default_uuid, max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'workspaces',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.CharField(default=knowledge.models.default_uuid, max_length=64, primary_key=True, serialize=False)),
                ('title', models.CharField(default='Untitled', max_length=300)),
                ('content_json', models.JSONField(default=knowledge.models.default_tiptap_json)),
                ('plain_text', models.TextField(blank=True, default='')),
                ('content_hash', models.CharField(blank=True, default='', max_length=64)),
                ('position', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notebook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='knowledge.notebook')),
            ],
            options={
                'db_table': 'pages',
                'ordering': ['position', 'title'],
            },
        ),
        migrations.CreateModel(
            name='PageDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attached_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_documents', to='knowledge.document')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_documents', to='knowledge.page')),
            ],
            options={
                'db_table': 'page_documents',
                'ordering': ['-attached_at'],
                'unique_together': {('page', 'document')},
            },
        ),
        migrations.AddField(
            model_name='document',
            name='pages',
            field=models.ManyToManyField(related_name='documents', through='knowledge.PageDocument', to='knowledge.page'),
        ),
        migrations.AddField(
            model_name='notebook',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notebooks', to='knowledge.workspace'),
        ),
    ]
