# Generated by Django 5.2.17 on 2026-08-15 04:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

import knowledge.models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagedocument',
            name='document',
            field=models.ForeignKey(db_column='document_id', on_delete=django.db.models.deletion.CASCADE, related_name='page_documents', to='knowledge.document'),
        ),
        migrations.AlterField(
            model_name='pagedocument',
            name='page',
            field=models.ForeignKey(db_column='page_id', on_delete=django.db.models.deletion.CASCADE, related_name='page_documents', to='knowledge.page'),
        ),
        migrations.CreateModel(
            name='ChatThread',
            fields=[
                ('id', models.CharField(default=knowledge.models.default_uuid, max_length=64, primary_key=True, serialize=False)),
                ('scope', models.CharField(default='workspace', max_length=20)),
                ('title', models.CharField(default='Nueva conversación', max_length=250)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notebook', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_threads', to='knowledge.notebook')),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_threads', to='knowledge.page')),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_threads', to='knowledge.workspace')),
            ],
            options={
                'db_table': 'chat_threads',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.CharField(default=knowledge.models.default_uuid, max_length=64, primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=20)),
                ('content', models.TextField()),
                ('sources_json', models.JSONField(blank=True, default=list)),
                ('attachments_json', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='knowledge.chatthread')),
            ],
            options={
                'db_table': 'chat_messages',
                'ordering': ['created_at'],
            },
        ),
    ]
