# Generated by Django 5.2.17 on 2026-08-15 04:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0002_alter_pagedocument_document_alter_pagedocument_page_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotebookDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attached_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('document', models.ForeignKey(db_column='document_id', on_delete=django.db.models.deletion.CASCADE, related_name='notebook_documents', to='knowledge.document')),
                ('notebook', models.ForeignKey(db_column='notebook_id', on_delete=django.db.models.deletion.CASCADE, related_name='notebook_documents', to='knowledge.notebook')),
            ],
            options={
                'db_table': 'notebook_documents',
                'ordering': ['-attached_at'],
                'unique_together': {('notebook', 'document')},
            },
        ),
        migrations.CreateModel(
            name='WorkspaceDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attached_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('document', models.ForeignKey(db_column='document_id', on_delete=django.db.models.deletion.CASCADE, related_name='workspace_documents', to='knowledge.document')),
                ('workspace', models.ForeignKey(db_column='workspace_id', on_delete=django.db.models.deletion.CASCADE, related_name='workspace_documents', to='knowledge.workspace')),
            ],
            options={
                'db_table': 'workspace_documents',
                'ordering': ['-attached_at'],
                'unique_together': {('workspace', 'document')},
            },
        ),
    ]
