# Generated by Django 5.2.17 on 2026-08-15 10:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

import knowledge.models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0003_notebookdocument_workspacedocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotebookArtifact',
            fields=[
                ('id', models.CharField(default=knowledge.models.default_uuid, max_length=64, primary_key=True, serialize=False)),
                ('artifact_type', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=250)),
                ('content', models.TextField()),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('notebook', models.ForeignKey(db_column='notebook_id', on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='knowledge.notebook')),
            ],
            options={
                'db_table': 'notebook_artifacts',
                'ordering': ['-created_at'],
            },
        ),
    ]
