# Generated by Django 5.2.17 on 2026-08-15 19:31

import django.utils.timezone
from django.db import migrations, models

import knowledge.models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0004_notebookartifact'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentMemory',
            fields=[
                ('id', models.CharField(default=knowledge.models.default_uuid, max_length=64, primary_key=True, serialize=False)),
                ('category', models.CharField(default='user_preference', max_length=50)),
                ('content', models.TextField()),
                ('source', models.CharField(default='chat_auto', max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'agent_memories',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentSkill',
            fields=[
                ('id', models.CharField(default=knowledge.models.default_uuid, max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(max_length=300)),
                ('instructions', models.TextField()),
                ('category', models.CharField(default='general', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'agent_skills',
                'ordering': ['name'],
            },
        ),
    ]
