# Generated by Django 6.1 on 2026-08-16 10:20

import django.utils.timezone
import knowledge.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0006_appconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiUsageLog',
            fields=[
                ('id', models.CharField(default=knowledge.models.default_uuid, max_length=64, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('category', models.CharField(db_index=True, max_length=30)),
                ('action', models.CharField(blank=True, default='', max_length=100)),
                ('provider', models.CharField(default='openrouter', max_length=50)),
                ('model', models.CharField(blank=True, default='', max_length=150)),
                ('status', models.CharField(default='success', max_length=20)),
                ('error_message', models.TextField(blank=True, default='')),
                ('input_tokens', models.IntegerField(default=0)),
                ('output_tokens', models.IntegerField(default=0)),
                ('total_tokens', models.IntegerField(default=0)),
                ('cost_usd', models.FloatField(blank=True, null=True)),
                ('request_count', models.IntegerField(default=1)),
                ('duration_ms', models.IntegerField(blank=True, null=True)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'api_usage_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
