# Generated by Django 6.1 on 2026-08-17 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0007_apiusagelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='appconfig',
            name='allow_cross_scope_promotion',
            field=models.BooleanField(default=False),
        ),
    ]
