# Generated by Django 6.1 on 2026-08-17 09:58

from django.db import migrations


def copy_docs_to_notebook_level(apps, schema_editor):
    """Sources were previously attachable at page, notebook, or workspace level; this app now
    only supports notebook-level attachment. Copy every existing page/workspace link forward into
    notebook_documents (deduplicated via get_or_create) before the old link tables are dropped
    below. Page-level links resolve to their own page's notebook; workspace-level links resolve to
    a single deterministic notebook (first by position, then created_at) rather than being fanned
    out to every notebook in the workspace, since sources should stay separated per notebook."""
    PageDocument = apps.get_model("knowledge", "PageDocument")
    WorkspaceDocument = apps.get_model("knowledge", "WorkspaceDocument")
    NotebookDocument = apps.get_model("knowledge", "NotebookDocument")
    Notebook = apps.get_model("knowledge", "Notebook")

    for pd in PageDocument.objects.select_related("page").all():
        NotebookDocument.objects.get_or_create(notebook_id=pd.page.notebook_id, document_id=pd.document_id)

    for wd in WorkspaceDocument.objects.all():
        target = Notebook.objects.filter(workspace_id=wd.workspace_id).order_by("position", "created_at").first()
        if target is not None:
            NotebookDocument.objects.get_or_create(notebook_id=target.id, document_id=wd.document_id)


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0008_appconfig_allow_cross_scope_promotion'),
    ]

    operations = [
        migrations.RunPython(copy_docs_to_notebook_level, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='document',
            name='pages',
        ),
        migrations.AlterUniqueTogether(
            name='workspacedocument',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='workspacedocument',
            name='document',
        ),
        migrations.RemoveField(
            model_name='workspacedocument',
            name='workspace',
        ),
        migrations.RemoveField(
            model_name='appconfig',
            name='allow_cross_scope_promotion',
        ),
        migrations.DeleteModel(
            name='PageDocument',
        ),
        migrations.DeleteModel(
            name='WorkspaceDocument',
        ),
    ]
