# Generated by Django 5.2.17 on 2026-08-20 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0009_migrate_docs_to_notebook_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatthread',
            name='history_json',
            field=models.TextField(blank=True, default=''),
        ),
    ]
