# Generated by Django 5.2.17 on 2026-08-25 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0010_chatthread_history_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='appconfig',
            name='language',
            field=models.CharField(default='es', max_length=10),
        ),
    ]
