from django.urls import path

from knowledge import views

urlpatterns = [
    path("", views.console_view, name="console"),
    path("health", views.health_view, name="health"),
    path("api/settings", views.app_settings_view, name="app_settings_view"),
    path("api/workspaces", views.create_workspace, name="create_workspace"),
    path("api/workspaces/<str:workspace_id>", views.workspace_detail_dispatch, name="workspace_detail_dispatch"),
    path("api/workspaces/<str:workspace_id>/tree", views.workspace_tree, name="workspace_tree"),
    path("api/notebooks", views.create_notebook, name="create_notebook"),
    path("api/notebooks/<str:notebook_id>", views.notebook_detail_dispatch, name="notebook_detail_dispatch"),
    path("api/pages", views.create_page, name="create_page"),
    path("api/pages/<str:page_id>", views.page_detail_dispatch, name="page_detail_dispatch"),
    path("api/pages/<str:page_id>/pdf", views.download_page_pdf_view, name="download_page_pdf_view"),
    path("api/pages/<str:page_id>/documents", views.page_documents, name="page_documents"),
    path("api/pages/<str:page_id>/documents/<str:document_id>", views.attach_document, name="attach_document"),
    path("api/pages/<str:page_id>/attachments", views.upload_page_attachment, name="upload_page_attachment"),
    path("api/sources", views.list_or_add_sources, name="list_or_add_sources"),
    path("api/documents/<str:document_id>", views.document_detail_dispatch, name="document_detail_dispatch"),
    path("api/artifacts/generate", views.generate_artifact_view, name="generate_artifact_view"),
    path("api/artifacts/generate-stream", views.generate_artifact_stream_view, name="generate_artifact_stream_view"),
    path("api/ai/inline-action", views.inline_ai_action_view, name="inline_ai_action_view"),
    path("api/notebooks/<str:notebook_id>/artifacts", views.notebook_artifacts_list_view, name="notebook_artifacts_list_view"),
    path("api/artifacts/<str:artifact_id>", views.delete_notebook_artifact_view, name="delete_notebook_artifact_view"),
    path("api/artifacts/<str:artifact_id>/pdf", views.download_artifact_pdf_view, name="download_artifact_pdf_view"),
    path("api/artifacts/<str:artifact_id>/media", views.serve_artifact_media_view, name="serve_artifact_media_view"),
    path("api/omni-search", views.omni_search_view, name="omni_search_view"),
    path("api/memories", views.list_or_create_memories_view, name="list_or_create_memories_view"),
    path("api/memories/<str:memory_id>", views.delete_memory_view, name="delete_memory_view"),
    path("api/skills", views.list_or_create_skills_view, name="list_or_create_skills_view"),
    path("api/skills/<str:skill_id>", views.delete_skill_view, name="delete_skill_view"),
    path("api/threads", views.list_or_create_threads, name="list_or_create_threads"),
    path("api/threads/<str:thread_id>", views.thread_detail_dispatch, name="thread_detail_dispatch"),
    path("api/threads/<str:thread_id>/messages", views.get_thread_messages, name="get_thread_messages"),
    path("ingest", views.ingest_file, name="ingest"),
    path("search", views.search_view, name="search"),
    path("chat/stream", views.chat_stream_view, name="chat_stream"),
    path("documents", views.documents_list, name="documents"),
    path("api/documents/<str:document_id>/file", views.serve_document_file, name="serve_document_file"),
    path("api/usage/summary", views.usage_summary_view, name="usage_summary_view"),
    path("api/usage/logs", views.usage_logs_view, name="usage_logs_view"),
]
